
services:

  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
    volumes:
      - spina-postgres:/var/lib/postgresql/data

  spina_dev:
    build:
      context: .
      args:
        ENVIRONMENT: development
    environment:
      DATABASE_URL: postgresql://postgres@postgres
    command: >
      sh -c "rails active_storage:install &&
            rails db:migrate &&
            rails db:create &&
            rails assets:precompile &&
            /usr/bin/tail -f /dev/null"
    depends_on:
      - postgres
      - spina_prod
    ports:
      - '3001:3000'
    volumes:
      - spina-dev:/app

  spina_prod:
    build:
      context: .
      args:
        ENVIRONMENT: production
    environment:
      DATABASE_URL: postgresql://postgres@postgres
    command: >
      sh -c "rails active_storage:install &&
            rails db:migrate &&
            rails db:create &&
            rails assets:precompile &&
            /usr/bin/tail -f /dev/null"
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    volumes:
      - spina-prod:/app

volumes:
  spina-postgres:
  spina-dev:
  spina-prod: