
services:

  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
    volumes:
      - spina-postgres:/var/lib/postgresql/data

  spina_dev:
    build:
      context: .
    environment:
      DATABASE_URL: postgresql://postgres@postgres
    volumes:
      - ./:/app
    depends_on:
      - postgres
      - spina_prod
    ports:
      - '3001:3000'

  spina_prod:
    build:
      context: .
      args:
        ENVIRONMENT: production
    environment:
      DATABASE_URL: postgresql://postgres@postgres
    volumes:
      - ./:/app
    depends_on:
      - postgres
    ports:
      - '3000:3000'

volumes:
  spina-postgres: