version: "3.9"

services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: spina
      POSTGRES_PASSWORD: spinA@2024
    ports: 
      - '5432:5432'
    volumes:
      - spina-postgres:/var/lib/postgresql/data

  spina:
    build:
      context: .
    volumes:
      - ./spina:/opt/app
    links:
      - postgres
    ports:
      - '3000:3000'

volumes:
  spina-postgres: