version: "3.9"

services:

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 2s
      timeout: 3s
      retries: 10
    volumes:
      - spina-postgres:/var/lib/postgresql/data
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql

  spina_dev:
    build:
      context: .
      args:
        ENVIRONMENT: development
    volumes:
      - ./spina:/opt/app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '3001:3000'

  # spina_prod:
  #   build:
  #     context: .
  #     args:
  #       ENVIRONMENT: production
  #   volumes:
  #     - ./spina:/opt/app
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   ports:
  #     - '3000:3000'

volumes:
  spina-postgres: